# Generated by Django 4.0.1 on 2022-02-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
