# Generated by Django 4.0.1 on 2022-02-28 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_books_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
